# -*- coding: utf-8 -*-
"""Data_cleaning_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBVlwOhTwKp9rmcc4ETx1QdWHrVpM1y7
"""

import os
import pandas as pd
import numpy as np

# File path shown in the Colab Files panel
file_path = "/content/new_data_set1.csv"

# Verify that the file exists
if not os.path.exists(file_path):
    raise FileNotFoundError(
        f"File not found: {file_path}. "
        "Check that new_data_set1.csv is visible in the Colab Files panel."
    )

# Read the CSV file
try:
    df = pd.read_csv(file_path)
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding="latin-1")

print("Dataset loaded successfully.")
print(f"File: {file_path}")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("Exact column names:\n")
for number, column in enumerate(df.columns, start=1):
    print(f"{number}. {column!r}")

print("DataFrame information:\n")
df.info()

missing_summary = pd.DataFrame({
    "data_type": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_percentage": (df.isna().mean() * 100).round(2),
    "non_missing_count": df.notna().sum(),
    "unique_values_including_missing": df.nunique(dropna=False)
}).sort_values(
    by="missing_count",
    ascending=False
)
display(missing_summary)

# Temporarily parse dates for validation.
# This does NOT overwrite df["date"] yet.
parsed_dates = pd.to_datetime(
    df["date"],
    format="%m/%d/%Y",
    errors="coerce"
)

print("DATE VALIDATION RESULTS")
print("-" * 60)
print(f"Total rows: {len(df):,}")
print(f"Successfully parsed dates: {parsed_dates.notna().sum():,}")
print(f"Invalid or missing dates: {parsed_dates.isna().sum():,}")

if parsed_dates.notna().any():
    print(f"Earliest date: {parsed_dates.min().date()}")
    print(f"Latest date: {parsed_dates.max().date()}")

print(f"Already in chronological order: {parsed_dates.is_monotonic_increasing}")
print(f"Duplicate dates: {parsed_dates.duplicated().sum():,}")

if parsed_dates.isna().sum() > 0:
    print("\nInvalid or unrecognized date values:")
    display(df.loc[parsed_dates.isna(), ["date"]].head(20))
else:
    print("\nAll date values match the expected format: month/day/year.")

target_column = "arrivals"
print("TARGET COLUMN VALIDATION")
print("-" * 60)
print(f"Target column: {target_column}")
print(f"Data type: {df[target_column].dtype}")
print(f"Missing values: {df[target_column].isna().sum():,}")
print(f"Zero values: {(df[target_column] == 0).sum():,}")
print(f"Negative values: {(df[target_column] < 0).sum():,}")
print(f"Minimum value: {df[target_column].min():,.0f}")
print(f"Maximum value: {df[target_column].max():,.0f}")
print(f"Mean value: {df[target_column].mean():,.2f}")
print(f"Median value: {df[target_column].median():,.2f}")

print("\nFirst 10 target observations:")
display(df[["date", target_column]].head(10))

print("\nLast 10 target observations:")
display(df[["date", target_column]].tail(10))

print("LOCATION COLUMN CHECK")
print("-" * 60)
print(f"Missing values: {df['location'].isna().sum():,}")
print(f"Number of unique values: {df['location'].nunique(dropna=False):,}")
print("\nLocation value counts:")
display(
    df["location"]
    .value_counts(dropna=False)
    .rename_axis("location")
    .reset_index(name="row_count")
)