# -*- coding: utf-8 -*-
"""Data_cleaning_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBVlwOhTwKp9rmcc4ETx1QdWHrVpM1y7
"""

import os
import pandas as pd
import numpy as np

# File path shown in the Colab Files panel
file_path = "/content/new_data_set1.csv"

# Verify that the file exists
if not os.path.exists(file_path):
    raise FileNotFoundError(
        f"File not found: {file_path}. "
        "Check that new_data_set1.csv is visible in the Colab Files panel."
    )

# Read the CSV file
try:
    df = pd.read_csv(file_path)
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding="latin-1")

print("Dataset loaded successfully.")
print(f"File: {file_path}")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("Exact column names:\n")
for number, column in enumerate(df.columns, start=1):
    print(f"{number}. {column!r}")

print("DataFrame information:\n")
df.info()

missing_summary = pd.DataFrame({
    "data_type": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_percentage": (df.isna().mean() * 100).round(2),
    "non_missing_count": df.notna().sum(),
    "unique_values_including_missing": df.nunique(dropna=False)
}).sort_values(
    by="missing_count",
    ascending=False
)
display(missing_summary)

# Temporarily parse dates for validation.
# This does NOT overwrite df["date"] yet.
parsed_dates = pd.to_datetime(
    df["date"],
    format="%m/%d/%Y",
    errors="coerce"
)

print("DATE VALIDATION RESULTS")
print("-" * 60)
print(f"Total rows: {len(df):,}")
print(f"Successfully parsed dates: {parsed_dates.notna().sum():,}")
print(f"Invalid or missing dates: {parsed_dates.isna().sum():,}")

if parsed_dates.notna().any():
    print(f"Earliest date: {parsed_dates.min().date()}")
    print(f"Latest date: {parsed_dates.max().date()}")

print(f"Already in chronological order: {parsed_dates.is_monotonic_increasing}")
print(f"Duplicate dates: {parsed_dates.duplicated().sum():,}")

if parsed_dates.isna().sum() > 0:
    print("\nInvalid or unrecognized date values:")
    display(df.loc[parsed_dates.isna(), ["date"]].head(20))
else:
    print("\nAll date values match the expected format: month/day/year.")

target_column = "arrivals"
print("TARGET COLUMN VALIDATION")
print("-" * 60)
print(f"Target column: {target_column}")
print(f"Data type: {df[target_column].dtype}")
print(f"Missing values: {df[target_column].isna().sum():,}")
print(f"Zero values: {(df[target_column] == 0).sum():,}")
print(f"Negative values: {(df[target_column] < 0).sum():,}")
print(f"Minimum value: {df[target_column].min():,.0f}")
print(f"Maximum value: {df[target_column].max():,.0f}")
print(f"Mean value: {df[target_column].mean():,.2f}")
print(f"Median value: {df[target_column].median():,.2f}")

print("\nFirst 10 target observations:")
display(df[["date", target_column]].head(10))

print("\nLast 10 target observations:")
display(df[["date", target_column]].tail(10))

print("LOCATION COLUMN CHECK")
print("-" * 60)
print(f"Missing values: {df['location'].isna().sum():,}")
print(f"Number of unique values: {df['location'].nunique(dropna=False):,}")
print("\nLocation value counts:")
display(
    df["location"
    .value_counts(dropna=False)
    .rename_axis("location")
    .reset_index(name="row_count")
)


# ------------------------------------------------------------
# STEP 2: BASIC DATA PREPARATION
# ------------------------------------------------------------

# 1. Preserve an in-memory copy of the originally loaded dataset.
#    This allows you to return to the raw version during this session.
df_raw = df.copy()

# 2. Record the row count before making changes.
rows_before = len(df)

# 3. Convert the confirmed date format from text to datetime.
df["date"] = pd.to_datetime(
    df["date"],
    format="%m/%d/%Y",
    errors="raise"
)

# 4. Sort explicitly by date to guarantee chronological order.
df = df.sort_values(
    by="date",
    ascending=True
).reset_index(drop=True)

# 5. Drop location because it has one constant value: Colombo.
df = df.drop(columns=["location"])

# 6. Basic verification output.
print("STEP 2: BASIC DATA PREPARATION COMPLETE")
print("-" * 60)
print(f"Rows before preprocessing: {rows_before:,}")
print(f"Rows after preprocessing: {len(df):,}")
print(f"Columns after preprocessing: {df.shape[1]:,}")
print(f"Date data type: {df['date'].dtype}")
print(f"Earliest date: {df['date'].min().date()}")
print(f"Latest date: {df['date'].max().date()}")
print(f"Chronological order: {df['date'].is_monotonic_increasing}")
print(f"Duplicate dates: {df['date'].duplicated().sum():,}")
print(f"'location' exists after dropping: {'location' in df.columns}")

print("\nFirst three rows after preparation:")
display(df.head(3))

print("\nLast three rows after preparation:")
display(df.tail(3))

# Expected daily frequency: one row for each calendar day.
date_gaps = df["date"].diff().dt.days
missing_calendar_days = date_gaps[date_gaps > 1]

print("DATE CONTINUITY CHECK")
print("-" * 60)
print(f"Expected daily records between first and last date: {(df['date'].max() - df['date'].min()).days + 1:,}")
print(f"Actual rows: {len(df):,}")
print(f"Number of gaps greater than one day: {len(missing_calendar_days):,}")

if len(missing_calendar_days) > 0:
    gap_rows = df.loc[missing_calendar_days.index, ["date"]].copy()
    gap_rows["previous_date"] = df["date"].shift(1).loc[missing_calendar_days.index].values
    gap_rows["gap_in_days"] = missing_calendar_days.values
    print("\nDetected date gaps:")
    display(gap_rows.head(20))
else:
    print("\nNo missing calendar dates were detected.")

exchange_rate_columns = [
    "usd_lkr",
    "rub_lkr",
    "inr_lkr",
    "gbp_lkr",
    "eur_lkr",
    "cny_lkr"
]

exchange_missing_summary = pd.DataFrame({
    "missing_count": df[exchange_rate_columns].isna().sum(),
    "missing_percentage": (
        df[exchange_rate_columns].isna().mean() * 100
    ).round(2),
    "first_available_date": df[exchange_rate_columns].apply(
        lambda column: df.loc[column.notna(), "date"].min()
    ),
    "last_available_date": df[exchange_rate_columns].apply(
        lambda column: df.loc[column.notna(), "date"].max()
    ),
    "first_missing_date": df[exchange_rate_columns].apply(
        lambda column: df.loc[column.isna(), "date"].min()
    ),
    "last_missing_date": df[exchange_rate_columns].apply(
        lambda column: df.loc[column.isna(), "date"].max()
    )
})
display(exchange_missing_summary)

# Create a row-level flag showing whether ALL six exchange-rate values are missing.
df["all_exchange_rates_missing"] = df[exchange_rate_columns].isna().all(axis=1)

# Display the first 15 records to inspect the initial missing values.
print("FIRST 15 ROWS: EXCHANGE-RATE INSPECTION")
display(
    df[
        ["date"] + exchange_rate_columns + ["all_exchange_rates_missing"]
    ].head(15)
)

# Show how many rows have all six rates missing versus at least one observed rate.
print("\nALL-EXCHANGE-RATES-MISSING COUNTS")
display(
    df["all_exchange_rates_missing"]
    .value_counts(dropna=False)
    .rename_axis("all_exchange_rates_missing")
    .reset_index(name="row_count")
)

# Identify complete all-rate-missing blocks in chronological order.
missing_block_id = (
    df["all_exchange_rates_missing"]
    .ne(df["all_exchange_rates_missing"].shift())
    .cumsum()
)
all_missing_blocks = (
    df.loc[df["all_exchange_rates_missing"]]
    .groupby(missing_block_id[df["all_exchange_rates_missing"]])
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        number_of_days=("date", "size")
    )
    .reset_index(drop=True)
)

print("\nALL-RATE MISSING BLOCK SUMMARY")
display(all_missing_blocks)

print("\nLongest all-rate missing blocks:")
display(
    all_missing_blocks
    .sort_values("number_of_days", ascending=False)
    .head(20)
)

# ------------------------------------------------------------
# STEP 3.1: LEAKAGE-SAFE EXCHANGE-RATE IMPUTATION
# ------------------------------------------------------------

# Preserve the original missingness before replacing any values.
# These flags can be kept as optional model features or audit columns.
for column in exchange_rate_columns:
    df[f"{column}_was_missing"] = df[column].isna().astype("int8")

# Count missing values before imputation.
exchange_missing_before = df[exchange_rate_columns].isna().sum()

# Forward-fill only: each missing value receives the most recent
# exchange rate available on an earlier date.
# No backward fill and no two-sided interpolation are used.
df[exchange_rate_columns] = df[exchange_rate_columns].ffill()

# Count missing values after imputation.
exchange_missing_after = df[exchange_rate_columns].isna().sum()

# Create a clear verification table.
exchange_imputation_check = pd.DataFrame({
    "missing_before": exchange_missing_before,
    "missing_after_forward_fill": exchange_missing_after,
    "values_filled": exchange_missing_before - exchange_missing_after
})

print("EXCHANGE-RATE IMPUTATION RESULTS")
print("-" * 70)
display(exchange_imputation_check)

print("\nRemaining missing exchange-rate cells by column:")
print(exchange_missing_after[exchange_missing_after > 0])

print("\nRows that still contain any missing exchange rate:")
remaining_exchange_missing_rows = df.loc[
    df[exchange_rate_columns].isna().any(axis=1),
    ["date"] + exchange_rate_columns
]
display(remaining_exchange_missing_rows)

print("\nExchange-rate values around the start of the series:")
display(
    df[
        ["date"] + exchange_rate_columns +
        [f"{column}_was_missing" for column in exchange_rate_columns]
    ].head(6)
)

print("\nExchange-rate values around the 2025-09 long missing block:")
display(
    df.loc[
        (df["date"] >= "2025-09-06") &
        (df["date"] <= "2025-09-21"),
        ["date"] + exchange_rate_columns +
        [f"{column}_was_missing" for column in exchange_rate_columns]
    ]
)

# ------------------------------------------------------------
# STEP 3.1: MARK START-OF-SERIES EXCHANGE-RATE INCOMPLETENESS
# ------------------------------------------------------------

# Flag rows where one or more exchange-rate values remain unavailable
# even after past-only forward-fill.
df["exchange_rates_complete"] = (
    df[exchange_rate_columns]
    .notna()
    .all(axis=1)
    .astype("int8")
)

# Create the inverse flag for easier inspection.
df["exchange_rates_incomplete"] = (
    1 - df["exchange_rates_complete"]
).astype("int8")

print("EXCHANGE-RATE COMPLETENESS CHECK")
print("-" * 70)

print("\nCompleteness counts:")
display(
    df["exchange_rates_complete"]
    .value_counts()
    .sort_index()
    .rename_axis("exchange_rates_complete")
    .reset_index(name="row_count")
)

print("\nRows with incomplete exchange-rate data after forward-fill:")
display(
    df.loc[
        df["exchange_rates_incomplete"] == 1,
        ["date"] + exchange_rate_columns +
        ["exchange_rates_complete", "exchange_rates_incomplete"]
    ]
)

print("\nFinal exchange-rate missing-value count:")
display(df[exchange_rate_columns].isna().sum().to_frame("remaining_missing_count"))


# ------------------------------------------------------------
# STEP 3.2: INSPECT GDP AND INFLATION MISSINGNESS
# ------------------------------------------------------------

macro_columns = [
    "gdp_per_capita",
    "inflation_rate"
]

# Summary of the real missingness pattern.
macro_missing_summary = pd.DataFrame({
    "missing_count": df[macro_columns].isna().sum(),
    "missing_percentage": (
        df[macro_columns].isna().mean() * 100
    ).round(2),
    "first_available_date": df[macro_columns].apply(
        lambda column: df.loc[column.notna(), "date"].min()
    ),
    "last_available_date": df[macro_columns].apply(
        lambda column: df.loc[column.notna(), "date"].max()
    ),
    "first_missing_date": df[macro_columns].apply(
        lambda column: df.loc[column.isna(), "date"].min()
    ),
    "last_missing_date": df[macro_columns].apply(
        lambda column: df.loc[column.isna(), "date"].max()
    )
})

print("GDP AND INFLATION MISSINGNESS SUMMARY")
print("-" * 70)
display(macro_missing_summary)

# Check whether both fields are missing on exactly the same dates.
same_missing_dates = (
    df["gdp_per_capita"].isna()
    == df["inflation_rate"].isna()
).all()

print(f"\nGDP and inflation missing on exactly the same dates: {same_missing_dates}")

# Identify continuous time blocks where both macroeconomic columns are missing.
both_macro_missing = df[macro_columns].isna().all(axis=1)

macro_block_id = (
    both_macro_missing
    .ne(both_macro_missing.shift())
    .cumsum()
)

macro_missing_blocks = (
    df.loc[both_macro_missing]
    .groupby(macro_block_id[both_macro_missing])
    .agg(
        start_date=("date", "min"),
        end_date=("date", "max"),
        number_of_days=("date", "size")
    )
    .reset_index(drop=True)
)

print("\nMISSING BLOCKS WHERE BOTH GDP AND INFLATION ARE MISSING")
display(macro_missing_blocks)

print("\nLongest missing blocks:")
display(
    macro_missing_blocks
    .sort_values("number_of_days", ascending=False)
    .head(20)
)

print("\nRows around the first macroeconomic missing date:")
first_macro_missing_date = df.loc[both_macro_missing, "date"].min()
display(
    df.loc[
        (df["date"] >= first_macro_missing_date - pd.Timedelta(days=5)) &
        (df["date"] <= first_macro_missing_date + pd.Timedelta(days=10)),
        ["date"] + macro_columns
    ]
)

# ------------------------------------------------------------
# STEP 3.2: LEAKAGE-SAFE MACROECONOMIC IMPUTATION
# ------------------------------------------------------------

# Preserve the original missingness before filling values.
for column in macro_columns:
    df[f"{column}_was_missing"] = df[column].isna().astype("int8")

# Record missing counts before filling.
macro_missing_before = df[macro_columns].isna().sum()

# Use only previously available values.
# This fills the 2026 trailing block with values known on 2025-12-31.
df[macro_columns] = df[macro_columns].ffill()

# Record missing counts after filling.
macro_missing_after = df[macro_columns].isna().sum()

# Display imputation results.
macro_imputation_check = pd.DataFrame({
    "missing_before": macro_missing_before,
    "missing_after_forward_fill": macro_missing_after,
    "values_filled": macro_missing_before - macro_missing_after
})

print("MACROECONOMIC IMPUTATION RESULTS")
print("-" * 70)
display(macro_imputation_check)

print("\nVerification around the 2025–2026 transition:")
display(
    df.loc[
        (df["date"] >= "2025-12-28") &
        (df["date"] <= "2026-01-05"),
        [
            "date",
            "gdp_per_capita",
            "inflation_rate",
            "gdp_per_capita_was_missing",
            "inflation_rate_was_missing"
        ]
    ]
)

print("\nRemaining missing values in macroeconomic columns:")
display(
    df[macro_columns]
    .isna()
    .sum()
    .to_frame("remaining_missing_count")
)

# ------------------------------------------------------------
# STEP 3.3: WEATHER DATA QUALITY CHECK
# ------------------------------------------------------------

weather_columns = [
    "temperature",
    "precipitation",
    "humidity",
    "wind_speed"
]

weather_quality_summary = pd.DataFrame({
    "missing_count": df[weather_columns].isna().sum(),
    "missing_percentage": (
        df[weather_columns].isna().mean() * 100
    ).round(2),
    "minimum": df[weather_columns].min(),
    "maximum": df[weather_columns].max(),
    "mean": df[weather_columns].mean().round(2),
    "median": df[weather_columns].median().round(2),
    "negative_value_count": (
        df[weather_columns] < 0
    ).sum()
})

print("WEATHER DATA QUALITY SUMMARY")
print("-" * 70)
display(weather_quality_summary)

print("\nWeather rows containing missing values:")
weather_missing_rows = df.loc[
    df[weather_columns].isna().any(axis=1),
    ["date"] + weather_columns
]
display(weather_missing_rows)

print("\nFirst five weather observations:")
display(df[["date"] + weather_columns].head())

print("\nLast five weather observations:")
display(df[["date"] + weather_columns].tail())

# ------------------------------------------------------------
# Save Person 1 output for Person 2
step3_path = "/content/step_3_missing_values_preprocessed.csv"
df.to_csv(step3_path, index=False, date_format="%Y-%m-%d")
print(f"Saved Person 1 output: {step3_path}")